---
- hosts: webservers
  tasks:
  - name: " create static website"
    synchronize:
      src: site/
      dest: /var/www/{{ domain }}/
      archive: no 
      checksum: yes
      recursive: yes
      delete: yes 
    become: no 